version: '3'
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
    networks:
      - belajar_docker_my_network

networks:
  belajar_docker_my_network:
    external: true

